// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq59MgeLStpCB0KdDZQrHD8lIjHtgIY3M',
    appId: '1:534962381497:web:119d00df28f9c8d053b168',
    messagingSenderId: '534962381497',
    projectId: 'msl-manager',
    authDomain: 'msl-manager.firebaseapp.com',
    storageBucket: 'msl-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUz87_6l-D3Ok02T3_W0PJEKw6jj-SS60',
    appId: '1:534962381497:android:913f3b5db41fd3a453b168',
    messagingSenderId: '534962381497',
    projectId: 'msl-manager',
    storageBucket: 'msl-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMXNxAhfDhR9ruBtbndU98OKwtaecSUBE',
    appId: '1:534962381497:ios:b0478ae4f73a6def53b168',
    messagingSenderId: '534962381497',
    projectId: 'msl-manager',
    storageBucket: 'msl-manager.firebasestorage.app',
    iosBundleId: 'com.example.mslManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMXNxAhfDhR9ruBtbndU98OKwtaecSUBE',
    appId: '1:534962381497:ios:b0478ae4f73a6def53b168',
    messagingSenderId: '534962381497',
    projectId: 'msl-manager',
    storageBucket: 'msl-manager.firebasestorage.app',
    iosBundleId: 'com.example.mslManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq59MgeLStpCB0KdDZQrHD8lIjHtgIY3M',
    appId: '1:534962381497:web:6800cf9c65d57a5853b168',
    messagingSenderId: '534962381497',
    projectId: 'msl-manager',
    authDomain: 'msl-manager.firebaseapp.com',
    storageBucket: 'msl-manager.firebasestorage.app',
  );
}
